project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - .nojekyll
    - slides/
    - images/
    - coursework/
    - files/

website:
  title: "Mingyuan You (Billy)"
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true

  navbar:
    collapse: true
    collapse-below: lg
    right:
      - text: "Homepage"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Coursework"
        href: coursework.qmd
      - text: "CV"
        href: cv.qmd
      - text: "References"
        href: references.qmd
      - text: "中文"
        href: index-zh.qmd
        id: lang-switch
      - icon: github
        href: "https://github.com/Jaojaobot"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css:
      - style.css
    include-after-body:
      - language-switch.html
    toc: true
    code-link: true

editor: visual
